# Generated by Django 4.2.5 on 2023-09-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_membershiprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipRequest',
        ),
    ]
